import React from 'react'

import '@/shared/assets/styles/global.scss'

import { Metadata } from 'next'

import AntdProvider from '@/providers/Antd'
import { IBMP } from '@/shared/assets/fonts/fonts'
import { Footer } from '@/widgets/footer/ui/footer'

export const metadata: Metadata = {
  title: 'Next app',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
      </head>
      <body className={`layout-root ${IBMP.className}`}>
        <AntdProvider>
          {/* <Navbar/> */}
          {children}
          <Footer/>
        </AntdProvider>
      </body>
    </html>
  )
}
